### ISSUE TITLE
Move package structure to rrtools

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/Reproducibility_in_Plant_Pathology#19]
@benmarwick has created a very nice R package for research compendia, [rrtools](https://github.com/benmarwick/rrtools).

I've used it elsewhere in my research, https://github.com/phytopathology/rice_awd_pests.

And since this project is already an R package focusing on reproducible research, it seems like a good idea to use the rrtools package to format this compendium.

**Comment by benmarwick** [comment]
Thanks, do let me know how rrtools fits into your conventions for making your work more reproducible. 

I've tried to make rrtools a toolkit for making it easier to do what I see people doing 'in the wild'. There are still a lot of open questions about what is the best or most natural way to organise a research compendium. Everyone has an opinion, but I'm most interested to see what people are actually doing to make their work more reproducible. 

One question that we're discussing right now is where to put the data. Keep it in the compendium pkg near the Rmd?  Use `data-raw/`? Have a separate data package with only the data files? Put the data in a repository, get a DOI, and load it into the compendium pkg with a line of script? Probably each discipline (even person!) will have slightly different preferences, and we may be able to automate some of the most common behaviours. My preference at the moment is to keep it near the main Rmd file, but that wont suit everyone, and might not be the best practice because it hides the data away a little. If you have any thoughts or observations I'd be most interested to know!

**Comment by adamhsparks** [comment]
In my [awd.rice.pests](https://github.com/phytopathology/rice_awd_pests) package, I've followed the `data_raw/` convention and created the final data files that reside in `data` and load them to create the vignettes. That seemed, to me, the most natural way of doing it since it is an R package.
