### ISSUE TITLE
Paper title needs to be decided on

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/Reproducibility_in_Plant_Pathology#53]
An early working title we had was: 
"What Does Reproducible Research Mean for Plant Pathology?"

We also had:
"How Can We Open Plant Pathology?"

Currently, it is:
"Insights Into Computational Reproducibility in Plant Pathology and a Way Forward"

The current version is appropriate for a paper, but we're leaning toward a letter to the editor, so this needs to be revisited with an eye toward that format.

**Comment by emdelponte** [comment]
My suggestion for the title:

"Reproducibility and plant pathology: where do we stand in and a way forward"

I like the idea of letter to the editor. In this case, I would place all tables in the supplemental materials and keep only the two figures in the main text. Alternatively, the material and methods could be shown as supplemental as well instead of appendix?

**Comment by emdelponte** [comment]
@adamhsparks see comments above

**Comment by zachary-foster** [comment]
Both the current title and @emdelponte 's suggestion sounds good to me.

**Comment by adamhsparks** [comment]
"Open science is coming to plant pathology, are we ready?"

**Comment by adamhsparks** [comment]
Renamed with "Reproducibility and plant pathology: where do we stand and a way forward"
